---
abstract: ~
author:
  - 'Wes Young, <wes@barely3am.com>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CIF-Archive-DataType-Plugin-ASN
no_index:
  directory:
    - inc
    - t
requires:
  CIF::Archive: 0.01_01
  Module::Pluggable: 3.6
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
